version: '2'

services:  
  nginx:
    image: nginx # need dockerfile to add config and rtmp module
    ports:
      - "1883:1883"
    restart: always
 
  obs:
    build: ./obs
    ports:
      - "80"

  studio-ui:
    image: ghcr.io/niek/obs-web
    ports:
      - 5900:5900