version: '2'

services:  
  nginx:
    build: ./nginx
    ports:
      - "1935:1935"
 
  obs:
    build: ./obs
    ports:
      - 4455:4455

  studio-ui:
    image: ghcr.io/niek/obs-web
    ports:
      - 5000:5000